name: PR @claude 自动执行任务

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  ai-task:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude')
    steps:
      - name: 获取完整仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置环境变量和Claude接口
        uses: anthropics/claude-code-action@v1
        env:
          ANTHROPIC_BASE_URL: "https://api.deepseek.com/anthropic"
          ANTHROPIC_API_KEY: sk-7ca61728d7b54f4ab8d0cc4ab8b66e93
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model: deepseek-v4-flash
